# Generated by Django 5.1.3 on 2024-12-09 14:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('judul', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='galeri_photos/')),
                ('deskripsi_detail', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Galeri',
            },
        ),
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('nama', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='guru_photos/')),
                ('deskripsi_singkat', models.TextField()),
                ('deskripsi_detail', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Guru',
            },
        ),
    ]
