# Generated by Django 5.1.3 on 2024-12-09 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildrenExhibitionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=10)),
                ('registration_status', models.CharField(choices=[('open', 'Daftar Sekarang'), ('limited', 'Tempat Terbatas'), ('closed', 'Pendaftaran Tutup')], default='open', max_length=20)),
            ],
            options={
                'verbose_name': 'Children Exhibition',
                'verbose_name_plural': 'Children Exhibitions',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='CookingClassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('instructor', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=10)),
                ('ticket_status', models.CharField(choices=[('available', 'Tiket Tersedia'), ('limited', 'Tiket Hampir Habis'), ('sold_out', 'Tiket Habis Terjual')], default='available', max_length=20)),
            ],
            options={
                'verbose_name': 'Cooking Class',
                'verbose_name_plural': 'Cooking Classes',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ParentingSeminarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('speaker', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=10)),
                ('ticket_status', models.CharField(choices=[('available', 'Tiket Tersedia'), ('limited', 'Tiket Hampir Habis'), ('sold_out', 'Tiket Habis Terjual')], default='available', max_length=20)),
            ],
            options={
                'verbose_name': 'Parenting Seminar',
                'verbose_name_plural': 'Parenting Seminars',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('age_range', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='program_images/')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramsCompetitionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('jenkel', models.CharField(choices=[('l', 'Laki-Laki'), ('p', 'Perempuan')], max_length=1, verbose_name='Jenis Kelamin')),
                ('tgl_lahir', models.DateField(verbose_name='Tanggal Lahir')),
                ('pesan', models.TextField()),
                ('agree', models.BooleanField(default=False, verbose_name='Saya setuju untuk mengikuti lomba dan mengikuti syarat dan ketentuan yang berlaku')),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_program', models.CharField(max_length=50)),
                ('description', models.TextField(default='Default description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='programs.program')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='Default description')),
                ('icon_class', models.CharField(max_length=100)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='programs.program')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon_class', models.CharField(max_length=100)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='programs.program')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='programs.program')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='teacher_photos/')),
                ('experience', models.CharField(max_length=255)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='programs.program')),
            ],
        ),
    ]
