# Generated by Django 5.1.3 on 2024-11-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_alamat_customuser_no_telp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('L', 'Pria'), ('P', 'Wanita')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='no_telp',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
