# Generated by Django 5.1.3 on 2024-12-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_gender_alter_customuser_no_telp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Laki-laki', 'Pria'), ('Perempuan', 'Wanita')], max_length=10, null=True),
        ),
    ]
