# Generated by Django 5.1.3 on 2024-12-09 02:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Username hanya boleh mengandung huruf, angka, dan spasi.', regex='^[\\w\\s]+$')]),
        ),
    ]
