# Generated by Django 5.1.3 on 2024-12-09 02:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='no_telp',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Nomor telepon tidak valid.', regex='^\\+?1?\\d{9,12}$')]),
        ),
    ]
