# Generated by Django 5.1.3 on 2024-12-09 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email'),
        ('users', '0015_alter_customuser_no_telp'),
    ]

    operations = [
    ]
