# Generated by Django 5.1.3 on 2024-12-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_child_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='akta_kelahiran',
            field=models.FileField(blank=True, null=True, upload_to='uploads/akta_kelahiran/'),
        ),
        migrations.AddField(
            model_name='child',
            name='ktp',
            field=models.FileField(blank=True, null=True, upload_to='uploads/ktp/'),
        ),
    ]
