# Generated by Django 5.1.3 on 2024-12-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimoni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('foto', models.FileField(upload_to='testimoni/')),
                ('keterangan', models.TextField()),
            ],
        ),
    ]
