# Generated by Django 5.1.3 on 2024-12-06 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimoni',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='testimoni',
            name='nama',
        ),
    ]
