# Generated by Django 5.1.3 on 2024-12-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_testimoni_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimoni',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 Bintang'), (2, '2 Bintang'), (3, '3 Bintang'), (4, '4 Bintang'), (5, '5 Bintang')], default=1),
        ),
    ]
