# Generated by Django 5.1.3 on 2024-12-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_fasilitas'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimoni',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
