# Generated by Django 5.1.3 on 2024-12-09 15:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pendaftaran',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('nama_ortu', models.CharField(max_length=100, verbose_name='Nama Orang Tua')),
                ('email', models.EmailField(max_length=254, verbose_name='Alamat Email')),
                ('nomor_wa', models.CharField(max_length=15, verbose_name='Nomor WhatsApp Orang Tua')),
                ('alamat', models.TextField(verbose_name='Alamat Orang Tua')),
                ('ktp', models.FileField(upload_to='uploads/ktp/', verbose_name='Upload KTP Orang Tua')),
                ('nama_anak', models.CharField(max_length=100, verbose_name='Nama Anak')),
                ('umur_anak', models.CharField(max_length=2, verbose_name='Umur Anak')),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, verbose_name='Jenis Kelamin')),
                ('akta_kelahiran', models.FileField(upload_to='uploads/akta_kelahiran/', verbose_name='Upload Akta Kelahiran Anak')),
                ('program', models.CharField(choices=[('infant', 'Infant Care (0-12 bulan)'), ('toddler', 'Toddler Program (1-2 tahun)'), ('preschool', 'Pre-school Program (3-4 tahun)'), ('prekindergarten', 'Pre-kindergarten (4-5 tahun)')], max_length=15, verbose_name='Program')),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('payment_url', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
