# Generated by Django 5.1.3 on 2024-12-10 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0001_initial'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendaftaran',
            name='fee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='programs.fee', verbose_name='Jenis Program'),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.program', verbose_name='Program'),
        ),
    ]
