# Generated by Django 5.1.3 on 2024-12-10 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0002_pendaftaran_fee_alter_pendaftaran_program'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftaran',
            name='fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.fee', verbose_name='Jenis Program'),
        ),
    ]
