# Generated by Django 5.1.3 on 2024-12-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0003_alter_pendaftaran_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftaran',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
