# Generated by Django 5.1.3 on 2024-12-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0004_alter_pendaftaran_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftaran',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
