# Generated by Django 5.1.3 on 2024-12-10 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0005_alter_pendaftaran_payment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendaftaran',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pendaftaran',
            name='nama_ortu',
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
