# Generated by Django 5.1.3 on 2024-12-10 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0007_remove_pendaftaran_user_pendaftaran_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftaran',
            name='nama_ortu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pendaftaran', to=settings.AUTH_USER_MODEL),
        ),
    ]
