# Generated by Django 5.1.3 on 2024-12-11 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0010_alter_pendaftaran_nama_ortu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendaftaran',
            name='akta_kelahiran',
        ),
        migrations.RemoveField(
            model_name='pendaftaran',
            name='alamat',
        ),
        migrations.RemoveField(
            model_name='pendaftaran',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pendaftaran',
            name='jenis_kelamin',
        ),
        migrations.RemoveField(
            model_name='pendaftaran',
            name='ktp',
        ),
        migrations.RemoveField(
            model_name='pendaftaran',
            name='nama_anak',
        ),
        migrations.RemoveField(
            model_name='pendaftaran',
            name='nama_ortu',
        ),
        migrations.RemoveField(
            model_name='pendaftaran',
            name='nomor_wa',
        ),
        migrations.RemoveField(
            model_name='pendaftaran',
            name='umur_anak',
        ),
    ]
