# Generated by Django 5.1.3 on 2024-12-11 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0011_remove_pendaftaran_akta_kelahiran_and_more'),
        ('users', '0025_child_akta_kelahiran_child_ktp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pendaftaran',
            name='nama_anak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.child', verbose_name='Nama Anak'),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='nama_ortu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nama Orang Tua'),
        ),
    ]
