# Generated by Django 5.1.3 on 2024-12-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0014_alter_pendaftaran_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftaran',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('success', 'Success')], default='pending', max_length=20),
        ),
    ]
